ПМ22-7 Седов Николай


## Задачи для совместного разбора

In [3]:
import numpy as np
import pandas as pd

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
arr = np.random.uniform(0, 20, (4, 7))
a_min = np.min(arr)
a_max = np.max(arr)
(arr-a_min)/(np.amax(arr)-a_min)

array([[0.51466482, 0.6604164 , 0.9902486 , 0.09126244, 0.        ,
        0.51862667, 0.36630026],
       [0.80588472, 0.15804911, 0.82407209, 0.11774105, 0.64385444,
        0.2923107 , 0.93677039],
       [0.52096594, 0.39484019, 0.72715749, 0.20467388, 0.57430606,
        0.12727777, 0.86783712],
       [1.        , 0.27244805, 0.11158115, 0.70083668, 0.85229462,
        0.12133955, 0.95138293]])

In [5]:
arr*(1/(a_max-a_min))-(a_min/(a_max-a_min))

array([[5.14664820e-01, 6.60416395e-01, 9.90248600e-01, 9.12624389e-02,
        6.93889390e-18, 5.18626674e-01, 3.66300264e-01],
       [8.05884722e-01, 1.58049109e-01, 8.24072093e-01, 1.17741045e-01,
        6.43854443e-01, 2.92310703e-01, 9.36770386e-01],
       [5.20965939e-01, 3.94840186e-01, 7.27157486e-01, 2.04673877e-01,
        5.74306058e-01, 1.27277768e-01, 8.67837121e-01],
       [1.00000000e+00, 2.72448047e-01, 1.11581152e-01, 7.00836680e-01,
        8.52294618e-01, 1.21339554e-01, 9.51382929e-01]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [6]:
arr = np.random.randint(0, 10, size=(8, 10))
arr

array([[8, 7, 2, 0, 8, 8, 4, 4, 2, 6],
       [8, 6, 2, 6, 2, 3, 4, 1, 7, 9],
       [0, 4, 8, 3, 7, 8, 3, 4, 8, 3],
       [9, 9, 1, 8, 8, 0, 8, 1, 6, 7],
       [6, 4, 6, 0, 4, 5, 8, 8, 5, 5],
       [2, 6, 8, 1, 7, 7, 6, 5, 6, 3],
       [6, 2, 2, 0, 0, 5, 3, 9, 9, 8],
       [0, 4, 6, 4, 9, 1, 0, 9, 2, 7]])

In [7]:
min_index = np.argmin(arr.sum(axis=1))
print(min_index)
arr[min_index, :]

7


array([0, 4, 6, 4, 9, 1, 0, 9, 2, 7])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [8]:
arr1 = np.random.randint(0, 10, size=10)
print(arr1)
arr2 = np.random.randint(0, 10, size=10)
print(arr2)
dist_auto = np.linalg.norm(arr1-arr2)
print(dist_auto)

dist_manual = np.sum((arr1-arr2) ** 2) ** (1/2)
print(dist_manual)

print(dist_auto == dist_manual)

[3 9 6 4 2 0 0 6 2 1]
[9 6 5 6 7 0 2 7 4 4]
9.643650760992955
9.643650760992955
True


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [9]:
a = np.matrix([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.matrix([[3, -1], [2, 1]])
c = np.matrix([[7, 21], [11, 8], [8, 4]])

"""
A*X*B=-C, при выражении X получаем:
X=A^-1*(-C)*B^-1
"""
result1 = np.linalg.inv(a) @ -c @ np.linalg.inv(b)
result1

matrix([[ 1.00000000e+00,  5.32907052e-16],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [10]:
data = np.loadtxt("./minutes_n_ingredients.csv",dtype=int, delimiter=",", skiprows=1)
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [11]:
col = 1
print(f"Мин: {np.min(data[:, col])}\nМакс:{np.max(data[:, col])}\nМедиана:{np.median(data[:, col])}\n")

col = 2
print(f"Мин: {np.min(data[:, col])}\nМакс:{np.max(data[:, col])}\nМедиана:{np.median(data[:, col])}\n")



print(f"Мин: {np.min(data[:, 1:], axis=0)}\nМакс:{np.max(data[:, 1:], axis=0)}\nМедиана:{np.median(data[:, 1:], axis=0)}\n")


Мин: 0
Макс:2147483647
Медиана:40.0

Мин: 1
Макс:39
Медиана:9.0

Мин: [0 1]
Макс:[2147483647         39]
Медиана:[40.  9.]



3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [12]:
quant_value = 0.75
koshkas = np.quantile(data[:,1], quant_value)
mask = data[:,1] <= koshkas
data[mask]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [13]:
def counter(data: np.matrix) -> int:
    mask = data[:, 1] == 0
    return data[mask].shape[0], mask

count, mask = counter(data)
print(count)
new_data = data.copy()
print(new_data)
new_data[mask, 1] = 1
print(new_data)

count, mask = counter(new_data)
print(count)

479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [14]:
print(new_data.shape)
unique_rows = np.unique(new_data, axis=0)
print(unique_rows.shape)

(100000, 3)
(100000, 3)


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [15]:
unique, counts = np.unique(new_data[:, 2], return_counts=True)
print(f"Всего уникальных: {len(unique)}")
dict(zip(counts,unique))

Всего уникальных: 37


{13: 1,
 926: 2,
 2895: 3,
 5515: 4,
 7913: 5,
 9376: 6,
 10628: 7,
 10951: 8,
 10585: 9,
 9591: 10,
 8297: 11,
 6605: 12,
 4997: 13,
 3663: 14,
 2595: 15,
 1767: 16,
 1246: 17,
 790: 18,
 573: 19,
 376: 20,
 217: 21,
 161: 22,
 105: 23,
 69: 24,
 50: 25,
 28: 26,
 16: 28,
 12: 30,
 3: 35,
 1: 39,
 2: 33}

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [16]:
print(new_data.shape)
mask = new_data[:, 2] < 6
array_7 = new_data[mask]
print(array_7.shape)

(100000, 3)
(17262, 3)


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [17]:
results = (new_data[:,2]/new_data[:,1])
print(results)
np.max(results)

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [18]:
count =100
buffer = np.copy(data[data[:, 1].argsort()][::-1])
buffer = buffer[:count]
np.sum(buffer[:,2])/count

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [19]:
data[np.random.randint(data.shape[0], size=10), :]

array([[ 43581,     60,      6],
       [ 40346,     42,      4],
       [146079,     35,      7],
       [197013,    510,     14],
       [206087,     50,     12],
       [212207,     60,      6],
       [222936,     28,      7],
       [478398,     70,      8],
       [456129,     23,     13],
       [143918,     30,      3]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [20]:
current_mean = np.mean(new_data[:, 2])

mask = new_data[:, 2] < current_mean
result = new_data[mask]

print(new_data.shape)
print(result.shape)
print(f"{result.shape[0]*100/new_data.shape[0]}%")


(100000, 3)
(58802, 3)
58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [22]:
is_simple_mask = (new_data[:, 1] < 21) & (new_data[:, 2] < 6)
new_data = np.c_[new_data, is_simple_mask]
new_data

array([[127244,     60,     16,      0,      0],
       [ 23891,     25,      7,      0,      0],
       [ 94746,     10,      6,      0,      0],
       ...,
       [498432,     65,     15,      0,      0],
       [370915,      5,      4,      1,      1],
       [ 81993,    140,     14,      0,      0]])

13. Выведите процент "простых" рецептов в датасете

In [23]:
simple_count = new_data[new_data[:,3] == 1].shape[0]
all_count = new_data.shape[0]
print(simple_count)
print(all_count)

simple_count*100/all_count

9552
100000


9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [24]:
short_arr = new_data[new_data[:,1] < 10]
mask = (new_data[:,1] >= 10) & (new_data[:,1] < 20)
standard_arr = new_data[mask]
long_arr = new_data[20 <= new_data[:,1]]

#Нулевая ось - номер группы
#Первая ось - сам рецепт
#Вторая - хар-ки рецепта

crop_value = np.min([short_arr.shape[0], standard_arr.shape[0], long_arr.shape[0]])

result_arr = np.array([short_arr[:crop_value], standard_arr[:crop_value], long_arr[:crop_value]])
print(result_arr)

[[[ 67660      5      6      0      0]
  [366174      7      9      0      0]
  [204134      5      3      1      1]
  ...
  [420725      5      3      1      1]
  [  4747      1      9      0      0]
  [370915      5      4      1      1]]

 [[ 94746     10      6      0      0]
  [ 33941     18      9      0      0]
  [446597     15      5      1      1]
  ...
  [  9831     15      7      0      0]
  [335859     12     14      0      0]
  [256812     10      3      1      1]]

 [[127244     60     16      0      0]
  [ 23891     25      7      0      0]
  [157911     60     14      0      0]
  ...
  [168901     25      7      0      0]
  [392339     35     13      0      0]
  [206732     45     10      0      0]]]
