In [1]:
import numpy as np
import sympy as sp
import random
sp.init_printing()

1. Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [15]:
# A = np.array([[i for i in range(j,j+7)]for j in range(1,100)])
A = np.array([range(i, i + 7) for i in [1,11, 21,31,41,51,61,71,81,91,101]])
A

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

2. Средствами numpy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [22]:
a = []
for i in range(2,22,2):
    a.append(i*(i+1))
print(a)

[6, 20, 42, 72, 110, 156, 210, 272, 342, 420]


3. Создать две матрицы 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первой матрицы, которые больше соответсвующих (по расположению) значений второй матрицы. Подсчитать сумму этих значений.

In [19]:
A = np.array([[random.randint(1,10) for i in range(3)] for j in range(30)])
B = np.array([[random.randint(1,10) for i in range(3)] for j in range(30)])


array([[ 4,  9,  8],
       [ 6,  3,  2],
       [ 6,  3,  7],
       [10,  9,  8],
       [ 8,  5,  4],
       [ 6,  1,  6],
       [ 6,  1,  6],
       [ 4,  4, 10],
       [ 7,  3,  5],
       [ 3,  3,  4],
       [10,  2,  1],
       [ 8,  7,  3],
       [ 2,  4,  6],
       [ 3,  1,  8],
       [ 3,  3,  3],
       [ 6,  9,  3],
       [ 5,  3,  2],
       [ 4,  8,  6],
       [ 9,  1, 10],
       [ 9,  1,  5],
       [ 4,  1,  5],
       [ 6,  9,  3],
       [ 3, 10,  5],
       [ 1,  1,  4],
       [ 9,  3,  2],
       [ 1,  7, 10],
       [ 8, 10, 10],
       [ 5,  5,  7],
       [ 1,  3,  5],
       [ 7,  3,  1]])

4. Написать функцию, которая для целых значений n и m будет возвращать матрицу размера n на m, заполненную текстурой размера 2 на 2 состоящей из следующий значений:

```
0 1

2 3

```

Пример для n=5 и m = 4:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [5]:
np.array([[i%2 + (j%2)*2 for i in range(5)] for j in range(4)])

array([[0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2],
       [0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2]])

5. При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [6]:
A = np.array([[random.randint(0,10) for i in range(20)] for j in range(20)])
A

array([[ 6,  6,  4,  1,  3,  9,  9,  0,  7, 10, 10,  4,  5,  5,  5, 10,
         3,  8,  3, 10],
       [ 4,  6, 10,  8, 10,  9,  3,  2,  5, 10,  1,  2,  0,  1,  2,  1,
         4, 10,  0,  1],
       [ 2,  7,  4,  2,  3,  2,  5,  1,  1,  9,  4,  4,  6,  8,  9,  5,
         4,  5,  3,  0],
       [ 2,  8,  0,  1,  6,  7,  5, 10,  6,  5,  5,  3,  8,  9,  5,  7,
        10,  1,  9,  7],
       [ 9,  4,  9,  3,  1,  4,  4,  3,  5,  0,  8,  6,  2,  3,  2,  4,
        10,  9,  2,  9],
       [ 1,  1,  3,  1,  0, 10, 10,  4,  8,  5,  4,  5,  6,  7,  6,  0,
         4,  1,  8, 10],
       [10, 10, 10,  2, 10,  1,  1,  7,  1,  8, 10,  0,  5,  1, 10,  1,
         8,  5,  4,  4],
       [ 1,  9,  3,  2,  8,  6,  3,  4,  7,  1, 10,  3,  0, 10,  1,  0,
         8,  7,  8,  0],
       [10,  3, 10,  7,  8, 10,  4,  8,  2,  6,  2,  2,  3,  1,  5,  7,
         4, 10,  6,  4],
       [ 3,  7,  9,  5,  5,  7,  4,  1,  8,  0,  6,  7,  5,  0,  9,  1,
         8,  7, 10,  6],
       [ 7,  7,  4,  3,  9, 10

6. Имеется массив из 10 названий городов. При помощи прихотливой индексации сгенерировать последовательность из 100 элементов представляющих случайный выбор из названий городов.

In [7]:
np.random.choice(['Moscow', 'London', 'Paris', 'Berlin', 'Madrid', 'Rome', 'Prague', 'Vienna', 'Warsaw', 'Budapest'], 100)

array(['Madrid', 'Paris', 'Madrid', 'Warsaw', 'Madrid', 'Budapest',
       'Prague', 'Rome', 'Moscow', 'Rome', 'Moscow', 'Madrid', 'Warsaw',
       'Moscow', 'Madrid', 'Budapest', 'Budapest', 'Budapest', 'Warsaw',
       'Moscow', 'Madrid', 'Madrid', 'London', 'London', 'Budapest',
       'Prague', 'Berlin', 'London', 'Berlin', 'Vienna', 'Madrid',
       'Berlin', 'Rome', 'Berlin', 'Prague', 'Warsaw', 'Moscow', 'Prague',
       'Madrid', 'Vienna', 'Rome', 'Madrid', 'Madrid', 'Rome', 'Prague',
       'Warsaw', 'Rome', 'Moscow', 'Moscow', 'London', 'Madrid', 'Warsaw',
       'Rome', 'Rome', 'London', 'London', 'Rome', 'Berlin', 'Rome',
       'Prague', 'Moscow', 'London', 'Budapest', 'Madrid', 'Paris',
       'Rome', 'Vienna', 'Paris', 'Berlin', 'Prague', 'Paris', 'Warsaw',
       'Berlin', 'Rome', 'Moscow', 'Rome', 'Madrid', 'Rome', 'Moscow',
       'Prague', 'Rome', 'Vienna', 'Prague', 'Prague', 'Moscow', 'Warsaw',
       'Rome', 'Berlin', 'Berlin', 'Warsaw', 'Berlin', 'Paris', 'Berlin

7. Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)) добиться расставки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [8]:
np.zeros((8,8))


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

8. Создать двухмерный массив 20 на 3, содержащийслучайные целые числа от 0 до 100. Интерпретируя массив как 20 векторов из 3х компонент, отсортировать массив по длине векторов.

9. Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]. При решении задачи применить технику распространения.

10. Создать массив из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в массиве. Опредлить индекс этого значения.

11. Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

12. Задать два двухмерных массива ar1 и ar2 размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максиум из двух значений, находящихся на аналогичной позиции в массивах ar1, ar2.